//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyundaiAutomobileDealer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HyundaiEntities : DbContext
    {
        public HyundaiEntities()
            : base("name=HyundaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_hyundai_1334712_roles> tbl_hyundai_1334712_roles { get; set; }
        public virtual DbSet<tbl_hyundai_login_master> tbl_hyundai_login_master { get; set; }
        public virtual DbSet<tbl_hyundai_prod_category> tbl_hyundai_prod_category { get; set; }
        public virtual DbSet<tbl_hyundai_product_1334712> tbl_hyundai_product_1334712 { get; set; }
    
        public virtual int usp_delete_tbl_hyundai_product_1334712(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_delete_tbl_hyundai_product_1334712", productIDParameter);
        }
    
        public virtual int usp_save_tbl_hyundai_product_1334712(Nullable<int> productID, string productName, Nullable<int> productCategoryID, Nullable<decimal> unitPrice, Nullable<int> totalNumberAvailable, string description, ObjectParameter iD_out)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var productCategoryIDParameter = productCategoryID.HasValue ?
                new ObjectParameter("ProductCategoryID", productCategoryID) :
                new ObjectParameter("ProductCategoryID", typeof(int));
    
            var unitPriceParameter = unitPrice.HasValue ?
                new ObjectParameter("UnitPrice", unitPrice) :
                new ObjectParameter("UnitPrice", typeof(decimal));
    
            var totalNumberAvailableParameter = totalNumberAvailable.HasValue ?
                new ObjectParameter("TotalNumberAvailable", totalNumberAvailable) :
                new ObjectParameter("TotalNumberAvailable", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_save_tbl_hyundai_product_1334712", productIDParameter, productNameParameter, productCategoryIDParameter, unitPriceParameter, totalNumberAvailableParameter, descriptionParameter, iD_out);
        }
    
        public virtual ObjectResult<usp_view_tbl_hyundai_product_1334712_Result> usp_view_tbl_hyundai_product_1334712()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_view_tbl_hyundai_product_1334712_Result>("usp_view_tbl_hyundai_product_1334712");
        }
    
        public virtual ObjectResult<usp_viewbyid_tbl_hyundai_product_1334712_Result> usp_viewbyid_tbl_hyundai_product_1334712(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_viewbyid_tbl_hyundai_product_1334712_Result>("usp_viewbyid_tbl_hyundai_product_1334712", productIDParameter);
        }
    }
}
