//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyundaiAutomobileDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_hyundai_product_1334712
    {
        [Key]
        public int ProductID { get; set; }
        //[Display(Name="Product Name")]
        //[Required(ErrorMessage="Please enter the Product Name")]
        //    [Required]
        public string ProductName { get; set; }
        //[Display(Name = "Product Category")]
        //[Required(ErrorMessage = "Please enter the Product Category")]
        //[Required]
        
        public Nullable<int> ProductCategoryID { get; set; }
        //[Display(Name = "Unit Price")]
        //[Required]
        //[RegularExpression("[^0-9]", ErrorMessage = "Unit Price must be numeric")]
        //[Range(1, 30)]
        public decimal UnitPrice { get; set; }
        //[Display(Name = "Total Number Available")]
        //[Required]
        //[RegularExpression("[^0-9]", ErrorMessage = "Total number available must be numeric")]
        public int TotalNumberAvailable { get; set; }
        //[Display(Name="Description")]
        public string Description { get; set; }
    
        public virtual tbl_hyundai_prod_category tbl_hyundai_prod_category { get; set; }
    }
}
