//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyundaiAutomobileDealer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hyundai_login_master
    {
        public int LoginID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserRoleID { get; set; }
    
        public virtual tbl_hyundai_1334712_roles tbl_hyundai_1334712_roles { get; set; }
    }
}
