//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyundaiAutomobileDealer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hyundai_1334712_roles
    {
        public tbl_hyundai_1334712_roles()
        {
            this.tbl_hyundai_login_master = new HashSet<tbl_hyundai_login_master>();
        }
    
        public int role_code { get; set; }
        public string role_name { get; set; }
    
        public virtual ICollection<tbl_hyundai_login_master> tbl_hyundai_login_master { get; set; }
    }
}
