//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyundaiAutomobileDealer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hyundai_prod_category
    {
        public tbl_hyundai_prod_category()
        {
            this.tbl_hyundai_product_1334712 = new HashSet<tbl_hyundai_product_1334712>();
        }
    
        public int ProductCategoryID { get; set; }
        public string ProductCategoryName { get; set; }
    
        public virtual ICollection<tbl_hyundai_product_1334712> tbl_hyundai_product_1334712 { get; set; }
    }
}
